# Generated by Django 5.2 on 2025-04-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conovauser',
            name='role',
            field=models.CharField(blank=True, choices=[('learners', 'Learners'), ('employee', 'Employee'), ('admin', 'Admin')], max_length=10),
        ),
    ]
