# Generated by Django 5.2 on 2025-04-17 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.RenameField(
            model_name='room',
            old_name='room_plan',
            new_name='room_img',
        ),
        migrations.RenameField(
            model_name='workspace',
            old_name='capacity',
            new_name='floor_nos',
        ),
        migrations.AddField(
            model_name='room',
            name='x_coordinate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='y_coordinate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seat',
            name='y_coordinate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conovauser',
            name='role',
            field=models.CharField(blank=True, choices=[('learners', 'Learners'), ('employee', 'Employee'), ('admin', 'Admin')], default='employee', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='seatbooking',
            unique_together={('user', 'seat')},
        ),
        migrations.CreateModel(
            name='AvailabilitySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=5)),
                ('is_available', models.BooleanField(default=False)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.room')),
                ('seat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.seat')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.workspace')),
            ],
            options={
                'ordering': ['day'],
                'unique_together': {('workspace', 'room', 'seat', 'day')},
            },
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
