# Generated by Django 5.2 on 2025-04-14 05:29

import cloudinary_storage.storage
import core.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_conovauser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conovauser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='conovauser',
            name='last_name',
        ),
        migrations.AddField(
            model_name='conovauser',
            name='avatar',
            field=models.ImageField(default='', storage=cloudinary_storage.storage.MediaCloudinaryStorage, upload_to=core.utils.rename_avatar),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conovauser',
            name='full_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conovauser',
            name='personal_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='conovauser',
            name='qr_code_image',
            field=models.ImageField(default='', storage=cloudinary_storage.storage.MediaCloudinaryStorage, upload_to=core.utils.rename_qr_code),
            preserve_default=False,
        ),
    ]
