# Generated by Django 5.2 on 2025-04-18 11:56

import cloudinary_storage.storage
import core.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_workspace_location_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availabilityschedule',
            options={'default_related_name': 'availability', 'ordering': ['day']},
        ),
        migrations.AlterUniqueTogether(
            name='availabilityschedule',
            unique_together={('workspace', 'room', 'day')},
        ),
        migrations.AddField(
            model_name='seat',
            name='x_coordinate',
            field=models.FloatField(blank=True, help_text='Coordinate of room relative to the X-axis.', null=True),
        ),
        migrations.AlterField(
            model_name='availabilityschedule',
            name='day',
            field=models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], help_text='Day of the week e.g MON, TUE, WED', max_length=5),
        ),
        migrations.AlterField(
            model_name='availabilityschedule',
            name='end_time',
            field=models.TimeField(blank=True, help_text='The time booking should ends for the day', null=True),
        ),
        migrations.AlterField(
            model_name='availabilityschedule',
            name='is_available',
            field=models.BooleanField(default=False, help_text='Status of the day'),
        ),
        migrations.AlterField(
            model_name='availabilityschedule',
            name='room',
            field=models.ForeignKey(blank=True, help_text='The room you are adding availability schedule to.', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.room'),
        ),
        migrations.AlterField(
            model_name='availabilityschedule',
            name='start_time',
            field=models.TimeField(blank=True, help_text='The time booking should start for the day', null=True),
        ),
        migrations.AlterField(
            model_name='availabilityschedule',
            name='workspace',
            field=models.ForeignKey(blank=True, help_text='The workspace you are adding availability schedule to', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.workspace'),
        ),
        migrations.AlterField(
            model_name='conovauser',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Profile picture', null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage, upload_to=core.utils.rename_file),
        ),
        migrations.AlterField(
            model_name='conovauser',
            name='email',
            field=models.EmailField(help_text='Email address', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='conovauser',
            name='full_name',
            field=models.CharField(help_text='Full name', max_length=100),
        ),
        migrations.AlterField(
            model_name='conovauser',
            name='role',
            field=models.CharField(blank=True, choices=[('learners', 'Learners'), ('employee', 'Employee'), ('admin', 'Admin'), ('manager', 'Manager')], default='employee', max_length=10),
        ),
        migrations.AlterField(
            model_name='floor',
            name='floor_no',
            field=models.IntegerField(help_text="Floor number e.g 'Floor 1' "),
        ),
        migrations.AlterField(
            model_name='floor',
            name='floorplan',
            field=models.ImageField(help_text='Floor plan Image', storage=cloudinary_storage.storage.MediaCloudinaryStorage, upload_to=core.utils.rename_file),
        ),
        migrations.AlterField(
            model_name='floor',
            name='workspace',
            field=models.ForeignKey(help_text='The workspace you are adding the floor to', on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='core.workspace'),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.ForeignKey(help_text='The floor number you adding the room to. e.g Floor 1', on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='core.floor'),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_available',
            field=models.BooleanField(default=False, help_text='Status of the room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_required_approval',
            field=models.BooleanField(default=False, help_text='Does the room requires approval.'),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_restricted',
            field=models.BooleanField(default=False, help_text='Is the room restricted to users.'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_capacity',
            field=models.IntegerField(help_text='The number of people room can accomodate.'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_img',
            field=models.ImageField(help_text='The image of the room.', storage=cloudinary_storage.storage.MediaCloudinaryStorage, upload_to=core.utils.rename_file),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_no',
            field=models.IntegerField(help_text='The number of the room e.g 1, 2, e.t.c'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(help_text='Type of room e.g conference.', max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='x_coordinate',
            field=models.FloatField(blank=True, help_text='Coordinate of room relative to the X-axis.', null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='y_coordinate',
            field=models.FloatField(blank=True, help_text='Coordinate of room relative to the Y-axis.', null=True),
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='ends_at',
            field=models.DateTimeField(help_text='The time and date when the booking ends'),
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='meeting_description',
            field=models.TextField(help_text='Meeting description'),
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='meeting_title',
            field=models.CharField(help_text='The title of the meeting to be held in the room', max_length=200),
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='room',
            field=models.ForeignKey(help_text='The seat that is being booked', on_delete=django.db.models.deletion.CASCADE, to='core.room'),
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='start_at',
            field=models.DateTimeField(help_text='The time and date booking starts from'),
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='confirmed', help_text='The status of the booking e.g confirmed, pending, cancelled', max_length=100),
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='teams',
            field=models.ManyToManyField(help_text='users that would be present in the meeting.', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='seat',
            name='is_available',
            field=models.BooleanField(default=False, help_text='Status of the room'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='room',
            field=models.ForeignKey(help_text='The floor number you adding the seat to. e.g Floor 1', on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='core.floor'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_img',
            field=models.ImageField(help_text='The image of the room.', storage=cloudinary_storage.storage.MediaCloudinaryStorage, upload_to=core.utils.rename_file),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_no',
            field=models.CharField(help_text='Seat number e.g 15, 15c, 23a, e.t.c.', max_length=100),
        ),
        migrations.AlterField(
            model_name='seat',
            name='y_coordinate',
            field=models.FloatField(blank=True, help_text='Coordinate of room relative to the Y-axis.', null=True),
        ),
        migrations.AlterField(
            model_name='seatbooking',
            name='ends_at',
            field=models.DateTimeField(help_text='The time and date when the booking ends'),
        ),
        migrations.AlterField(
            model_name='seatbooking',
            name='seat',
            field=models.ForeignKey(help_text='The seat that is being booked', on_delete=django.db.models.deletion.CASCADE, to='core.seat'),
        ),
        migrations.AlterField(
            model_name='seatbooking',
            name='start_at',
            field=models.DateTimeField(help_text='The time and date booking starts from'),
        ),
        migrations.AlterField(
            model_name='seatbooking',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='confirmed', help_text='The status of the booking e.g confirmed, pending, cancelled', max_length=100),
        ),
        migrations.AlterField(
            model_name='seatbooking',
            name='user',
            field=models.ForeignKey(help_text='The user booking a seat', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='floor_nos',
            field=models.IntegerField(help_text='Number of floors in the workspace building'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='location',
            field=models.CharField(help_text='Where the workspace is located', max_length=200),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='name',
            field=models.CharField(help_text='Name of the workspace', max_length=200),
        ),
        migrations.RemoveField(
            model_name='availabilityschedule',
            name='seat',
        ),
    ]
