# Generated by Django 5.2 on 2025-04-18 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_availabilityschedule_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='floor',
            unique_together={('floor_no', 'workspace')},
        ),
    ]
