# Generated by Django 5.2 on 2025-04-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_floor_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='floor',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='floor',
            constraint=models.UniqueConstraint(fields=('floor_no', 'workspace'), name='unique_floor_per_workspace'),
        ),
    ]
