# Generated by Django 5.2 on 2025-04-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_floor_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='room',
            new_name='floor',
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('room_no', 'floor', 'room_type'), name='unique_room_per_floor'),
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(fields=('floor', 'seat_no'), name='unique_seat_per_floor'),
        ),
    ]
