# Generated by Django 5.2 on 2025-04-18 20:09

import cloudinary_storage.storage
import core.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_room_seat_floor_room_unique_room_per_floor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conovauser',
            name='prefers_email_notification',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Status of the room'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Status of the room'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_img',
            field=models.ImageField(blank=True, help_text='The image of the room.', null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage, upload_to=core.utils.rename_file),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
