# Generated by Django 5.2 on 2025-04-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_conovauser_prefers_email_notification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombooking',
            name='ends_at',
            field=models.DateTimeField(blank=True, help_text='The time and date when the booking ends', null=True),
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='start_at',
            field=models.DateTimeField(blank=True, help_text='The time and date booking starts from', null=True),
        ),
        migrations.AlterField(
            model_name='seatbooking',
            name='ends_at',
            field=models.DateTimeField(blank=True, help_text='The time and date when the booking ends', null=True),
        ),
        migrations.AlterField(
            model_name='seatbooking',
            name='start_at',
            field=models.DateTimeField(blank=True, help_text='The time and date booking starts from', null=True),
        ),
    ]
