# Generated by Django 5.2 on 2025-04-18 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_roombooking_ends_at_alter_roombooking_start_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seatbooking',
            unique_together={('user', 'seat', 'status')},
        ),
    ]
