# Generated by Django 5.2 on 2025-04-19 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_seatbooking_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking', 'Booking'), ('invite', 'Invite')], default='booking', max_length=15),
            preserve_default=False,
        ),
    ]
