# Generated by Django 5.2 on 2025-04-19 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_notification_notification_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roombooking',
            options={},
        ),
        migrations.RemoveField(
            model_name='roombooking',
            name='teams',
        ),
        migrations.AddField(
            model_name='roombooking',
            name='created_by',
            field=models.ForeignKey(default='', help_text='user making a room booking', on_delete=django.db.models.deletion.CASCADE, related_name='created_roombookings', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roombooking',
            name='invited_users',
            field=models.ManyToManyField(related_name='room_invites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RoomBookingInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_accepted', models.BooleanField(default=False)),
                ('has_declined', models.BooleanField(default=False)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='core.roombooking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('members', models.ManyToManyField(related_name='teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
