# Generated by Django 5.2 on 2025-04-19 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_roombooking_options_remove_roombooking_teams_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombooking',
            name='room',
            field=models.ForeignKey(help_text='The seat that is being booked', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.room'),
        ),
    ]
