# Generated by Django 5.2 on 2025-04-22 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_created_at_attendance_check_in_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='location_lat',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='location_long',
        ),
    ]
