# Generated by Django 5.2 on 2025-04-23 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_attendance_location_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conovauser',
            name='temporary_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='conovauser',
            name='token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
