# Generated by Django 5.2 on 2025-04-23 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_conovauser_temporary_token_conovauser_token_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conovauser',
            name='personal_token',
        ),
        migrations.AlterField(
            model_name='conovauser',
            name='role',
            field=models.CharField(choices=[('learners', 'Learners'), ('employee', 'Employee'), ('admin', 'Admin'), ('manager', 'Manager')], default='employee', max_length=10),
        ),
    ]
