# Generated by Django 5.2 on 2025-04-23 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_conovauser_personal_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conovauser',
            name='temporary_token',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
