# Generated by Django 5.2 on 2025-04-23 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_conovauser_temporary_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='wordspace',
            field=models.ForeignKey(default=1, help_text='The workspace you are adding the room to e.g constain hub', on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='core.workspace'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seat',
            name='workspace',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='core.workspace'),
            preserve_default=False,
        ),
    ]
