# Generated by Django 5.2 on 2025-04-23 21:37

import cloudinary_storage.storage
import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_room_wordspace_seat_workspace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availabilityschedule',
            name='seat',
        ),
        migrations.RemoveField(
            model_name='room',
            name='wordspace',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='workspace',
        ),
        migrations.AlterField(
            model_name='conovauser',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage, upload_to=core.utils.rename_file),
        ),
    ]
