# Generated by Django 5.2 on 2025-04-23 22:10

import cloudinary_storage.storage
import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_availabilityschedule_seat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_img',
            field=models.ImageField(blank=True, help_text='The image of the room.', null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage, upload_to=core.utils.rename_file),
        ),
    ]
